- common.j
See https://www.hiveworkshop.com/threads/orderid2string-returns-null-after-loading-a-saved-game.336367/#post-3507470
> Same issue as UnitId2String

- Readme.md
<2 minutes of hate for Markdown>
Github didn't like words in <square brackets> after titles and ate them.
> Readme: fix @annotation sub-titles

- unit.j
Finished SetUnitColor
Clarified SetUnitVertexColor
Wrote SetUnitOwner
I surpassed the 80/100 chars per line limit. Do we enforce this strictly here?
> unit.j: fixes lep/jassdoc#19. SetUnitOwner, SetUnitColor, SetUnitVertexColor

- unit.j
Described/finished: SetHeroLevel, SelectHeroSkill, GetUnitAbilityLevel, SetUnitAbilityLevel, ReviveHero, ReviveHeroLoc, UnitAddAbility, UnitRemoveAbility.
Supersedes and closes lep/jassdoc#13 (issue for setunitabilitylevel) and lep/jassdoc#27 (PR)
Tested on 1.32.10
---
Hopefully I use markdown correctly here? Single new line = continuation after a space character? You see, Markdown and I aren't friends :angry:
> unit.j: Add 8 docs related to: hero level, ability, skill, revival

- region-location.j
Written: Rect, RectFromLoc, RemoveRect, SetRect, SetRectFromLoc,
MoveRectTo, MoveRectToLoc, GetRectCenterX, GetRectCenterY, GetRectMinX,
GetRectMinY, GetRectMaxX, GetRectMaxY
Expanded: GetWorldBounds
---
Tested on v1.32.10
Code snippets: https://github.com/Luashine/wc3-test-maps/commit/bc26ab983add3127ad63c4ed592cf745e48c3625
> @bug You can't create your own rectangle that would match the dimensions of `GetWorldBounds`. The maxX and maxY will be smaller by `16.0` than that of the world bounds.
Funny isn't it?
> @bug This can be used to move the rectangle outside of the map bounds, bypassing the limiting checks.
---
PS: Basically this is proof that the "golden age" of video games:
1. Had all the same software development problems
2. Gold versions were still buggy, but not as buggy as the …
> region-location.j: document 14 Rect functions (Rectangle)

- unit.j
Described the following functions:
UnitItemInSlot, UnitHasItem, UnitInventorySize, UnitRemoveItem,
UnitDropItemPoint, UnitDropItemTarget
UnitAddItem, UnitAddItemById, UnitAddItemToSlotById
UnitUseItem, UnitUseItemPoint, UnitUseItemTarget
Added info about a visual bug with SetUnitColor
---
Fixes #34. I think now the entire unit's item usage API is documented :tada:
> unit.j: add 12 unit item/inventory functions, bug in SetUnitColor

- Blizzard.j
- game-event-api.j
- timer.j
- trigger.j
I do not have time and motivation to describe these two in-depth, but I wanted to add the table lest I forget it (and I was asked by Codemonkey too)
Is this OK? (eyes looking at #45 :eyes: )
Source:
https://www.hiveworkshop.com/threads/high-speed-triggers-or-a-slow-triggerregistertimereventperiodic.341024/
> Add execution frequency table for TimerStart and TriggerRegisterTimerEvent

- common.j
- map-setup.j
Base game speed can only be set via a .wgc file (Warcraft 3 Game
Configuration) that you can trigger by testing your map from within the
AI editor.
As always doing avantgarde work on a 20yo game :)
PS: Tool coming soon to automate creation of a .wgc file and launch the game with it. The WE seems totally broken for this with Refunded.
Explanation of .wcg testing: https://www.hiveworkshop.com/threads/how-to-run-maps-with-high-gamespeed.37255/
.wcg format will be sent as a PR there: https://github.com/ChiefOfGxBxL/WC3MapSpecification
> gamespeed: describe mechanics of base game speed

- Blizzard.j
- boolexpr.j
- builtin-types.j
- common.j
- effects.j
- force.j
- game-event-api.j
- group.j
- map-setup.j
- misc.j
- player.j
- random.j
- sound.j
- string.j
- timer.j
- trigger.j
- ui.j
- unit.j
- visuals.j
- widget.j
Most of the previous work was copy-pasted with adaptations. Some already existing descriptions were merged (improved upon).
Link:
https://wc3modding.info/index.php?action=profile;u=8882;area=showposts;start=0
---
In most cases I replaced the previous description with the new one, where I think it was clearer. Open to discussion.
Also I don't remember what we settled upon for BJ descriptions, lep. Was it to not add one-line docs to BJ functions which are obvious from the source code? That's alright as long as the original BJ code is exported and displayed in an IDE as part of the doc.
> Merge City17's wc3modding.info jassdoc contributions

- Blizzard.j
- builtin-types.j
- common.ai
- player.j
Fixes #71 
---
Common.ai: import and merge Starquizer's & moyack's docs
https://wc3modding.info/jassdoc/475/
Permission was granted by moyack.
The formatting was adapted, phrasing mostly changed to fit our jassdoc
style. For functions where the wording was unclear, the descriptions
were not touched or, at least, not paraphrased.
Added @bug note to GetAllyCount: not 24-player compatible.
---
> Common.ai: Original comment:
> // This is not the full common.ai just the natives which one can use in
> // normal jass scripts according to
>  <https://www.thehelper.net/threads/working-ai-natives.127331/>
>  // To use these you have to define them explicitly.
I double-checked the above, all of it is in there.
> Import wc3modding.info's jassdoc (common.ai)

- common.j
- fog-of-war.j
There're a couple things I dont like about it, most importantly the terminology. I want to discuss this again and seriously.
This is called the Fog of War API. The FOW itself has 3 states (quoting my first draft here):
---
- `FOG_OF_WAR_MASKED` (1): Black mask, an unexplored map area.
- If "Masked areas are partially visible" is enabled in Map Properties, unexplored areas are shown in dark grey. You can see the terrain, but no units.
- If disabled, unexplored areas are black and not visible.
- `FOG_OF_WAR_FOGGED` (2): Haze, a previously explored
map area that is currently not visible.
- You can see the terrain, but no units.
- `FOG_OF_WAR_VISIBLE` (4): A fully visible map area.
- Other (non-existent) fog types do nothing.
---
This seems fine until you begin dealing with individual …
> Document Fog of War API

- common.j
- destructable.j
- player-based-event-api.j
- unit-based-event-api.j
- widget.j
This line might struck your eye:
> A widget is an "interactive game object" with HP, **possibly an inventory** etc.
That's because the target in [UnitDropItemTarget](https://lep.duckdns.org/app/jassbot/doc/UnitDropItemTarget) is actually a widget :thinking:
> Describe Widget API

- multiboard.j
- timer-dialog.j
- unit.j
- visuals.j
From commit messages:
---
Testing code:
https://github.com/Luashine/wc3-test-maps/blob/1fd3cdaed228d5906a442bab27a8a9f4ce18ca55/README.md#timerdialog-api-tests
---
Previously I incorrectly described the r,g,b,a color values as if they
were clamped to (0,255). This is not the case. The input color value is
actually normalized with "value mod 256" or something similar, like an
integer division.
The result is that you get the magenta color for (-257, -256, -257) as
if you entered (255,0,255). The same applies to TimerDialogSetTitleColor
and probably other APIs of this kind.
Relatably, the float angles of unit facing are also normalized to be in
360 range.
Test code:
mb = CreateMultiboard()
-- yes, it's mod
MultiboardSetTitleTextColor(mb, -257, -256, -257, 255)
MultiboardSetTitleText(mb, …
> Describe Timer Dialog API

- unit.j
If you use this function to select a unit after calling ClearSelection (like SelectUnitSingle does) and you have a unit sub-menu opened (like spellbook or build structure), the command buttons of the selected unit won't show until you select another unit.
> SelectUnit and ClearSelections bug

- ui.j
Tested it's correlation with EnableSelect native, turns out it's exactly the same.
Also, BlzIsSelection...Enabled natives return same values if set by EnableSelect as they would for BlzEnableSelections
> Blz Selection Natives addition

- effects.j
- ui.j
Clarified that Z is absolute, not relative to ground coordinate.
Changed AddSpecialEffect/Loc native description to a more accurate description regarding Z coordinate.
Described a 1.29 bug for BlzSetSpecialEffectX/Y/Z natives.
> Special Effects Z coordinate related additions

- unit.j
BlzGetUnitAbilityCooldownRemaining is inconsistent for Channel-based abilities and may return 0 even if on cooldown. May have something to do with order of ability learnt.
This was tested on version 1.35 by NightKnight.
> Add bug note

- common.ai
- common.j
From commit messages:
`git log -n 5 --format=%s%n%b`
Add SetUnitFacing and SetUnitFacingTimed
string.j: GetHandleId returns a valid index for removed objects
sound.j: StartSoundEx, fadeIn is unused
Source: TriggerHappy/BogdanW3
common.j: Add exact WE Version for 12/24-p switch, fixes
Source: TriggerHappy; verified that 1.29.0.8803 has WE Version = 6060
common.ai: DisplayTextIII is a no-op
Source: BogdanW3 on Hive Discord
---
The rebasing wasn't fun, git has only shown the regular merge conflict ONCE. Else it wanted me to make out differences from entire split .j files... These are from November 2022
SetUnitFacingTimed should need more work it's like #31 the duration value is non-sense. Should I create an issue to track this?
> Unit Facing, StartSoundEx, 12/24-player, GetHandleId, DisplayTextIII

- common.j
That PR missed two more places there:
- SetRect
- SetRectFromLoc
https://github.com/lep/jassdoc/pull/112
Tests:
https://github.com/Luashine/wc3-test-maps/tree/5a2502b58bba21bc98cfd2513842fc79503fb8f8#rect--rectangle--region--location-code
> Rect API: Complete 16 -> 32 fix from PR #112

- common.j
Test code:
https://github.com/Luashine/wc3-test-maps/blob/3c52ea0994efa6f4f6e9c294ff616955f6a91686/Boolean-expression-API/README.md
In particular this paragraph rewritten:
(EDIT: dear `@note` I am sorry for pinging you again LOL)
> `@note` **Lua:** Always returns a new handle unless the passed parameter is `nil`, in this case
it MAY return the same handle depending on unknown conditions (consecutive calls are likely to reuse previous handle).
> **Jass:** Returns same handle when creating multiple filters for the same function:
`Filter(function foo) == Filter(function foo)` ("foo" can be non-constant and constant).
> For this reason, do **not** destroy filterfuncs created with `Filter` in Jass,
in the best case it does nothing but in the worst case it would affect some internals.
> This …
> Boolexpr API: Describe handle edge-cases, add See refs

- common.j
`ForceEnumPlayers` broke my brain for a while.
I have not yet gone into player state and player slot state, so the description will be refined later because the enum skips player slots based on some logic.
Edit: Filtering function's crash in Lua is interpreted as "false", otherwise no error is thrown. It's silent
> Force API: describe DestroyForce, ForceEnumPlayers & small changes.

- common.j
Please re-check and reflect on the interpretation.
I marked `BlzQueueBuildOrderById` returning `true` as a note instead of a bug because enqueuing build orders without having the resources for the structure is actually allowed. But it should not be allowed as the first order, so it's debatable if `BlzQueueBuildOrderById` should return `false` in that case if the queue was empty.
> Add notes to Point and Build order functions

- common.j
If the duration is too low, while the unit is moving, those functions won't be effective. The 0.1 seems a bit magical, but I tested just below 0.1 in comparison and with different turn rates and movement types.
> Add note to SetUnitFacing, SetUnitFacingTimed

- common.j
I'll soon finish writing this "tutorial" on Hive: "How to control enemy player's units (for play testing)"
> common.j: Describe SetPlayerAlliance (enemy test)

- Blizzard.j
I decided to word it this way because these call some other functions prefixed with "Melee" and I didn't want to track down these. It should be a good starting point anyway if someone wanted to read this code.
> `@note` It is called directly by the default "Melee Initialization" trigger.
I don't think I will have note generation for these functions although they are defined in `triggerdata.txt`. I don't expect these to change in the coming years :joy:
> Add note to Melee Init functions

- common.j
For description see individual commit messages.
1. common.j: Add unitweaponintegerfield descriptions by Arxos
2. common.j: describe old crash in BlzSetUnitAbilityManaCost
3. common.j: describe old crash bug with BlzSetUnitAbilityCooldown
> Add unitweaponintegerfield descriptions and two 1.29.x crashes

- common.j
https://github.com/Luashine/wc3-test-maps/tree/master/GetSummonedUnit
Hey lep, I was not sure where to put the per-event descriptions for the getters. I chose and think it's better to put *what getters to use* under event constants, because there's only one event but many different getters. It's easier for editing due to the one-to-many relationship rather than many-to-many if I were to put the comment to each getter. But for usability like in IDE it'd be better to mirror relevant lines to the getter function descriptions, like when exporting or showing this.
> Doc for Summon events and getters

- common.j
Adds some infos for ALLIANCE_SHARED_CONTROL & ALLIANCE_SHARED_ADVANCED_CONTROL.
Mostly about ally Hero Icons at the left side of screen.
> common.j Add Info ALLIANCE_SHARED_CONTROL

- common.j
Test code 1:
```lua
do 
local units = {"hpea", "opeo", "uaco", "ewsp", "nmpe", "nhew", "nbee", "ogru"}
local skills = {'ANbu','AHbu','AEbu','AObu','AUbu','AGbu'}
function checkBuilderAbility(unitRawcode, skillCodes)
local newUnit = CreateUnit(Player(0), FourCC(unitRawcode), 0, 0, 90)
local outText = {"Unit(".. unitRawcode ..")"}
for i, skill in ipairs(skillCodes) do
table.insert(outText, 
string.format("%4s", GetUnitAbilityLevel(newUnit, FourCC(skill)))
)
end
print(table.concat(outText, ","))
end
local heading = string.format("%-12s %s", "Table:", table.concat(skills, ","))
print(heading)
for i = 1, #units do
checkBuilderAbility(units[i], skills)
end
print("----")
end
```
Manual test code 2:
```lua
hpea = CreateUnit(Player(0), FourCC("hpea"), 0, 0, 90)
print(DecUnitAbilityLevel(hpea, …
```
> Fixes #152 - GetUnitAbilityLevel and building abilities

- common.j
Testing setup has got to be like that:
- need all possible terrain elevations:
- flat 0, shallow water, deep water, hill
- flat elevating doodad (platform) or doodad stairs (there's a slope) or doodad bridge
I suggest to start by spawning stuff on the slope/platforms becauase these give "nice" odd height values. Then set locations back and forth between other terrain heights. If you still get the spawning platform's odd value, then it was reset.
**Tip:** your testing map SHOULD start on either a +1 hill or -1 shallow water. Otherwise you'll get confused like I was that it resets to Z=0 (default flat surface).
Tested functions:
set height, set Z, set loc, set position (x,y,z), set special effect matrix, reset special effect matrix. Only the SetX, SetY, SetLoc functions needed corrections. …
> SpecialEffect: clarify height reset for position changes

- common.j
a quick verification about this behavior:
> add a @bug about pausing a timer will clear its periodic flag

- common.j
Fixes #30 . Just changed wording and provided test code
uh, gotta delete branch after merging. should've probably used my fork and PR from there.
---
v2.0.2.22796
Lua test code:
```
function testEffectHeight()
local elevatedPosX, elevatedPosY = 65, 700
local groundLevelPosX, groundLevelPosY = -475, 360
local x, y = elevatedPosX, elevatedPosY
if sorceressSpawnElevatedZ then DestroyEffect(sorceressSpawnElevatedZ) end
sorceressSpawnElevatedZ = AddSpecialEffect([[units\human\sorceress\sorceress.mdx]], x, y)
local eff = sorceressSpawnElevatedZ
-- prints 256, 2-level high hill
print("spawn Z: ".. BlzGetLocalSpecialEffectZ(eff))
BlzSetSpecialEffectHeight(eff,43)
-- prints 43
print("Changed Height: ", BlzGetLocalSpecialEffectZ(eff))
BlzSetSpecialEffectZ(eff,42)
-- prints 42
print("Changed Z: ", …
```
> common.j: clarify BlzGetLocalSpecialEffectZ

- common.j
Add note that level param is 0-indexed. I hope the 1.31.1 note is not too much clutter?
Also added the bug annotation to all SetXXX fields. However I only tested as much as I showed in the code.
Finally, since I tested button positions, added those too.
> v2.0.3 Set Ability Field bug & button positions & 0-indexed ability level

- Readme.md
- common.j
duckdns has been unreliable at times and lep has had this new fancy domain for a while
PS: current opensearch.xml already points there, while previously added search engine links cannot be updated automatically. Though apparently there exists a directive that can be included in newer versions: https://developer.mozilla.org/en-US/docs/Web/XML/Guides/OpenSearch#supporting_automatic_updates_for_opensearch_description
workaround: remove search engine in browser settings and add it again from the main page of Jassbot
> Update domain in README

- common.j
Tested in 2.0.3.23025, although there has been a previous PTR 2.0.3.22994
PS: While fields that previously didn't work still have no effect as before (like `ABILITY_SF_ICON_RESEARCH` in test code), the values are set and reported correctly per ability instance.
https://lep.nrw/jassbot/doc/BlzSetAbilityStringLevelField test code here
> common.j: note ability level field fix in 2.0.3.23025 PTR

- common.j
Based on internal code, the function only works with single Latin letters and digits. All other characters are ignored.
Relevant code from disassembly:
```cpp
if ( (string[0] = *v5, string[1] = 0, SStrUpper(string), v7 = string[0], string[0] >= 48) && v7 <= OSKEY_9
|| v7 >= OSKEY_A && v7 <= OSKEY_Z )
```
Additionally, only the key down event is triggered by `ForceUIKey`, while key up events do not. Example for testing:
```lua
-- Only Is key down: true will be printed
local testTrigger = CreateTrigger()
BlzTriggerRegisterPlayerKeyEvent(testTrigger, GetLocalPlayer(), OSKEY_1, 0, true)
BlzTriggerRegisterPlayerKeyEvent(testTrigger, GetLocalPlayer(), OSKEY_1, 0, false)
TriggerAddAction(testTrigger, function()
print("Is key down: " .. tostring(BlzGetTriggerPlayerIsKeyDown()))
end) …
```
> ForceUIKey accepted keys and event limitations
